[project]
name = 'Tokenized-Financial-Inclusion-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credit-history]
path = 'contracts/credit-history.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-verification]
path = 'contracts/identity-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
